linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  cyclop:
    max-complexity: 35
    skip-tests: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 80 # This is super high value. We should gradually lower it to 30-40.

linters:
  enable:
    #- nolintlint
    #- unparam
    - bodyclose
    - dupl
    - forbidigo
    - gocognit
    - gocritic
    - gofmt
    - goimports
    - goimports
    - gosec
    - nakedret
    - revive
    - stylecheck
    - unconvert
  disable:
    #- gocognit
    - errorlint
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maintidx
    - maligned
    - nestif
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - scopelint
    - tagliatelle
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
