linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  cyclop:
    max-complexity: 35
    skip-tests: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 80 # This is super high value. We should gradually lower it to 30-40.

linters:
  enable:
    - gofmt
    - goimports
    - bodyclose
    - dupl
    - forbidigo
    - gocognit
    - gocritic
    - goimports
    - gosec
    - nakedret
    - nolintlint
    - revive
    - stylecheck
    - unconvert
    #- unparam
  disable:
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
